version: "3.0"

services:
    hadoop1:
        container_name: hadoop1     
        image: hadoop:1
        hostname: hadoop1
        stdin_open: true
        tty: true
        privileged: true
        ports:
            - "9870:9870"
            - "8088:8088"
        networks:
            hadoop_network:
                ipv4_address: 192.168.101.11

    hadoop2:
        container_name: hadoop2       
        image: hadoop:1
        hostname: hadoop2
        stdin_open: true
        tty: true
        privileged: true
        networks:
            hadoop_network:
                ipv4_address: 192.168.101.12 

    hadoop3:
        container_name: hadoop3       
        image: hadoop:1
        hostname: hadoop3
        stdin_open: true
        tty: true
        privileged: true
        networks:
            hadoop_network:
                ipv4_address: 192.168.101.13

    hadoop4:
        container_name: hadoop4       
        image: hadoop:1
        hostname: hadoop4
        stdin_open: true
        tty: true
        privileged: true
        networks:
            hadoop_network:
                ipv4_address: 192.168.101.14

    hadoop5:
        container_name: hadoop5       
        image: hadoop:1
        hostname: hadoop5
        stdin_open: true
        tty: true
        privileged: true
        networks:
            hadoop_network:
                ipv4_address: 192.168.101.15

networks:
  hadoop_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24