FROM centos:7
LABEL maintainer="gymbombom@kakao.com"
LABEL version="1.0.0" 
LABEL description="bitdata test"

######################################################################################################################################
# ARM
ARG JDK_ARCHIVE_FILE="openjdk-17.0.2_linux-aarch64_bin.tar.gz"
ARG JDK_ARCHIVE_FILE_11="zulu11.62.17-ca-jdk11.0.18-linux_aarch64.tar.gz"
ARG JDK_FILE_11="zulu11.62.17-ca-jdk11.0.18"
ARG LOGSTASH_ARCHIVE_FILE="logstash-8.6.2-linux-aarch64.tar.gz"
ARG KAFKA_ARCHIVE_FILE="kafka_2.13-3.4.0.tgz"
ARG HADOOP_ARCHIVE_FILE="hadoop-3.3.4.tar.gz"
ARG SPARK_ARCHIVE_FILE="spark-3.3.2-bin-hadoop3.tgz"
ARG ES_ARCHIVE_FILE="elasticsearch-8.6.2-linux-aarch64.tar.gz"
######################################################################################################################################
WORKDIR /root

# yum install
RUN echo "root:root" | chpasswd
RUN yum install wget -y
RUN yum install openssh-server openssh-clients openssh-askpass -y
RUN yum install sshpass -y
RUN yum install which -y
RUN yum install sudo -y

# wget 
RUN wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-aarch64_bin.tar.gz
RUN wget https://cdn.azul.com/zulu-embedded/bin/zulu11.62.17-ca-jdk11.0.18-linux_aarch64.tar.gz
RUN wget https://artifacts.elastic.co/downloads/logstash/logstash-8.6.2-linux-aarch64.tar.gz
RUN wget https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz
RUN wget --no-check-certificate https://dlcdn.apache.org/hadoop/common/hadoop-3.3.4/hadoop-3.3.4.tar.gz
RUN wget --no-check-certificate https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.2-linux-aarch64.tar.gz

# tar 
RUN tar -xvf ${JDK_ARCHIVE_FILE}
RUN mkdir ./${JDK_FILE_11} ; tar -xvf  ${JDK_ARCHIVE_FILE_11} -C ./${JDK_FILE_11} --strip-components 1
RUN tar -xvf ${LOGSTASH_ARCHIVE_FILE}
RUN tar -xvf ${KAFKA_ARCHIVE_FILE}
RUN tar -xvf ${HADOOP_ARCHIVE_FILE}
RUN tar -xvf ${SPARK_ARCHIVE_FILE}
RUN tar -xvf ${ES_ARCHIVE_FILE}


# rm
RUN rm -rf ${JDK_ARCHIVE_FILE}
RUN rm -rf ${JDK_ARCHIVE_FILE_11}
RUN rm -rf ${LOGSTASH_ARCHIVE_FILE}
RUN rm -rf ${KAFKA_ARCHIVE_FILE}
RUN rm -rf ${HADOOP_ARCHIVE_FILE}
RUN rm -rf ${SPARK_ARCHIVE_FILE}
RUN rm -rf ${ES_ARCHIVE_FILE}

RUN echo  "export JAVA_HOME='/root/jdk-17.0.2';" >> /root/.bashrc
RUN echo "export PATH=\$PATH:\$JAVA_HOME/bin;" >> /root/.bashrc
RUN source /root/.bashrc
######################################################################################################################################